"Correção src/components/SidebarDrawer/index.tsx(54,14): error TS2741: Property 'activeColor' is missing in type '{ key: any; text: any; icon: any; onClick: any; page: any; renderIndicator: (page: string) => Element; iconColor: string; }' but required in type 'MenuButtonProps'. e Limpeza do streaming"